In [2]:
import pandas as pd
df = pd.read_csv("platform_statistics_2026.csv")

# ==================================================
# PLATFORM STATISTICS DATA CLEANING
# ==================================================

# 1. Make a copy of the original dataset
platform = df.copy()


# --------------------------------------------------
# 2. Check original data
# --------------------------------------------------

print("Original rows:", len(platform))
print("Original columns:", len(platform.columns))

print("\nMissing values:")
print(platform.isnull().sum())


# --------------------------------------------------
# 3. Handle missing values
# --------------------------------------------------

# Numerical columns
numeric_columns = [
    "monthly_active_users_billions",
    "year_over_year_growth_pct",
    "avg_daily_time_minutes",
    "avg_engagement_rate_pct",
    "social_commerce_adoption_pct",
    "founded_year"
]

for col in numeric_columns:
    if col in platform.columns:
        platform[col] = platform[col].fillna(platform[col].median())


# Categorical columns
categorical_columns = [
    "platform",
    "primary_age_group",
    "primary_content_format",
    "headquarters_country",
    "data_source"
]

for col in categorical_columns:
    if col in platform.columns:
        platform[col] = platform[col].fillna("Unknown")


# --------------------------------------------------
# 4. Remove duplicate records
# --------------------------------------------------

platform.drop_duplicates(inplace=True)


# --------------------------------------------------
# 5. Create useful derived columns
# --------------------------------------------------

# Estimated daily active user value
platform["estimated_daily_users_billions"] = (
    platform["monthly_active_users_billions"] * 0.30
)


# Engagement score
platform["engagement_score"] = (
    platform["avg_engagement_rate_pct"] *
    platform["avg_daily_time_minutes"]
)


# Growth category
platform["growth_category"] = pd.cut(
    platform["year_over_year_growth_pct"],
    bins=[-float("inf"), 5, 10, float("inf")],
    labels=["Low Growth", "Medium Growth", "High Growth"]
)


# Social commerce category
platform["commerce_category"] = pd.cut(
    platform["social_commerce_adoption_pct"],
    bins=[-float("inf"), 20, 40, float("inf")],
    labels=["Low", "Medium", "High"]
)


# --------------------------------------------------
# 6. Calculate platform age
# --------------------------------------------------

current_year = 2026

platform["platform_age"] = (
    current_year - platform["founded_year"]
)


# --------------------------------------------------
# 7. Standardize column names
# --------------------------------------------------

platform.columns = (
    platform.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_", regex=False)
)


# --------------------------------------------------
# 8. Check cleaned data
# --------------------------------------------------

print("\n========================================")
print("CLEANED PLATFORM DATA")
print("========================================")

print("Original rows:", len(df))
print("Cleaned rows:", len(platform))
print("Columns:", len(platform.columns))

print("\nMissing values after cleaning:")
missing = platform.isnull().sum()

if missing.sum() == 0:
    print("No missing values")
else:
    print(missing[missing > 0])


# --------------------------------------------------
# 9. Display cleaned dataset
# --------------------------------------------------

print("\nFirst 5 rows:")
display(platform.head())


# --------------------------------------------------
# 10. Dataset information
# --------------------------------------------------

print("\nDataset Information:")
platform.info()

Original rows: 17
Original columns: 11

Missing values:
platform                         0
monthly_active_users_billions    0
year_over_year_growth_pct        0
avg_daily_time_minutes           0
primary_age_group                0
primary_content_format           0
avg_engagement_rate_pct          0
social_commerce_adoption_pct     0
headquarters_country             0
founded_year                     0
data_source                      0
dtype: int64

========================================
CLEANED PLATFORM DATA
========================================
Original rows: 17
Cleaned rows: 17
Columns: 16

Missing values after cleaning:
No missing values

First 5 rows:

,platform,monthly_active_users_billions,year_over_year_growth_pct,avg_daily_time_minutes,primary_age_group,primary_content_format,avg_engagement_rate_pct,social_commerce_adoption_pct,headquarters_country,founded_year,data_source,estimated_daily_users_billions,engagement_score,growth_category,commerce_category,platform_age
0,Facebook,3.07,2.5,33,25-34,Mixed/Video,1.5,60.9,USA,2004,Statista/Meta,0.921,49.5,Low Growth,High,22
1,Instagram,3.00,13.0,35,18-34,Reels/Stories,2.2,35.0,USA,2010,Meta/Reuters,0.900,77.0,High Growth,Medium,16
2,YouTube,2.58,5.5,48,18-49,Long/Short Video,1.9,22.0,USA,2005,Statista,0.774,91.2,Medium Growth,Medium,21
3,WhatsApp,3.00,4.0,28,25-44,Messaging,0.0,15.0,USA,2009,Meta,0.900,0.0,Low Growth,Low,17
4,TikTok,1.99,17.0,58,18-24,Short-Form Video,2.8,43.8,China,2016,Statista,0.597,162.4,High Growth,High,10

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   platform                        17 non-null     str
 1   monthly_active_users_billions   17 non-null     float64
 2   year_over_year_growth_pct       17 non-null     float64
 3   avg_daily_time_minutes          17 non-null     int64
 4   primary_age_group               17 non-null     str
 5   primary_content_format          17 non-null     str
 6   avg_engagement_rate_pct         17 non-null     float64
 7   social_commerce_adoption_pct    17 non-null     float64
 8   headquarters_country            17 non-null     str
 9   founded_year                    17 non-null     int64
 10  data_source                     17 non-null     str
 11  estimated_daily_users_billions  17 non-null     float64
 12  engagement_score                17 non-null     float64
 13  growth_category                 17 non-null     category
 14  commerce_category               17 non-null     category
 15  platform_age                    17 non-null     int64
dtypes: category(2), float64(6), int64(3), str(5)
memory usage: 1.8 KB

In [3]:
# Make a copy
platform = df.copy()


# --------------------------------------------------
# 1. Handle missing values
# --------------------------------------------------

# Numerical columns
platform["monthly_active_users_billions"] = (
    platform["monthly_active_users_billions"]
    .fillna(platform["monthly_active_users_billions"].median())
)

platform["year_over_year_growth_pct"] = (
    platform["year_over_year_growth_pct"]
    .fillna(platform["year_over_year_growth_pct"].median())
)

platform["avg_daily_time_minutes"] = (
    platform["avg_daily_time_minutes"]
    .fillna(platform["avg_daily_time_minutes"].median())
)

platform["avg_engagement_rate_pct"] = (
    platform["avg_engagement_rate_pct"]
    .fillna(platform["avg_engagement_rate_pct"].median())
)

platform["social_commerce_adoption_pct"] = (
    platform["social_commerce_adoption_pct"]
    .fillna(platform["social_commerce_adoption_pct"].median())
)


# --------------------------------------------------
# 2. Handle categorical missing values
# --------------------------------------------------

platform["primary_age_group"] = (
    platform["primary_age_group"].fillna("Unknown")
)

platform["primary_content_format"] = (
    platform["primary_content_format"].fillna("Unknown")
)

platform["headquarters_country"] = (
    platform["headquarters_country"].fillna("Unknown")
)


# --------------------------------------------------
# 3. Remove duplicate records
# --------------------------------------------------

platform.drop_duplicates(inplace=True)


# --------------------------------------------------
# 4. Create useful derived columns
# --------------------------------------------------

# Platform age
platform["platform_age"] = 2026 - platform["founded_year"]


# Engagement score
platform["engagement_score"] = (
    platform["avg_engagement_rate_pct"] *
    platform["avg_daily_time_minutes"]
)


# Growth category
platform["growth_category"] = pd.cut(
    platform["year_over_year_growth_pct"],
    bins=[-float("inf"), 5, 10, float("inf")],
    labels=["Low", "Medium", "High"]
)


# --------------------------------------------------
# 5. Standardize column names
# --------------------------------------------------

platform.columns = (
    platform.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_", regex=False)
)


# --------------------------------------------------
# 6. Check cleaned data
# --------------------------------------------------

print("Original rows:", len(df))
print("Cleaned rows:", len(platform))
print("Columns:", len(platform.columns))

print("\nMissing values:")
print(platform.isnull().sum()[platform.isnull().sum() > 0])

display(platform.head())

Original rows: 17
Cleaned rows: 17
Columns: 14

Missing values:
Series([], dtype: int64)

,platform,monthly_active_users_billions,year_over_year_growth_pct,avg_daily_time_minutes,primary_age_group,primary_content_format,avg_engagement_rate_pct,social_commerce_adoption_pct,headquarters_country,founded_year,data_source,platform_age,engagement_score,growth_category
0,Facebook,3.07,2.5,33,25-34,Mixed/Video,1.5,60.9,USA,2004,Statista/Meta,22,49.5,Low
1,Instagram,3.00,13.0,35,18-34,Reels/Stories,2.2,35.0,USA,2010,Meta/Reuters,16,77.0,High
2,YouTube,2.58,5.5,48,18-49,Long/Short Video,1.9,22.0,USA,2005,Statista,21,91.2,Medium
3,WhatsApp,3.00,4.0,28,25-44,Messaging,0.0,15.0,USA,2009,Meta,17,0.0,Low
4,TikTok,1.99,17.0,58,18-24,Short-Form Video,2.8,43.8,China,2016,Statista,10,162.4,High

In [14]:
db_engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/platform_analytics"
)

print("Connected to platform_analytics!")

Connected to platform_analytics!

In [19]:
username = "root"
password = "YOUR_MYSQL_PASSWORD"   # Enter your MySQL password
host = "localhost"
port = 3306

In [1]:
import sqlite3
import pandas as pd
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()
with open("platform_statistics.sql", "r") as file:
    sql_script = file.read()
cursor.executescript(sql_script)
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)
print("Tables in Database:")
print(tables)
# Get first table name
table_name = tables.iloc[0, 0]
# Read data
df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
print("\n===== HEAD =====")
print(df.head())
print("\n===== INFO =====")
df.info()
conn.close()

Tables in Database:
      name
0  mytable

===== HEAD =====
    platform  monthly_active_users_billions  year_over_year_growth_pct  \
0   Facebook                           3.07                        2.5
1  Instagram                           3.00                       13.0
2    YouTube                           2.58                        5.5
3   WhatsApp                           3.00                        4.0
4     TikTok                           1.99                       17.0

   avg_daily_time_minutes primary_age_group primary_content_format  \
0                      33             25-34            Mixed/Video
1                      35             18-34          Reels/Stories
2                      48             18-49       Long/Short Video
3                      28             25-44              Messaging
4                      58             18-24       Short-Form Video

   avg_engagement_rate_pct  social_commerce_adoption_pct headquarters_country  \
0                      1.5                          60.9                  USA
1                      2.2                          35.0                  USA
2                      1.9                          22.0                  USA
3                      0.0                          15.0                  USA
4                      2.8                          43.8                China

   founded_year    data_source
0          2004  Statista/Meta
1          2010   Meta/Reuters
2          2005       Statista
3          2009           Meta
4          2016       Statista

===== INFO =====
<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   platform                       17 non-null     str
 1   monthly_active_users_billions  17 non-null     float64
 2   year_over_year_growth_pct      17 non-null     float64
 3   avg_daily_time_minutes         17 non-null     int64
 4   primary_age_group              17 non-null     str
 5   primary_content_format         17 non-null     str
 6   avg_engagement_rate_pct        17 non-null     float64
 7   social_commerce_adoption_pct   17 non-null     float64
 8   headquarters_country           17 non-null     str
 9   founded_year                   17 non-null     int64
 10  data_source                    17 non-null     str
dtypes: float64(4), int64(2), str(5)
memory usage: 1.2 KB

In [8]:
import sqlite3
import pandas as pd

# --------------------------------------------------
# 1. Make platform DataFrame from df
# --------------------------------------------------

platform = df.copy()

# --------------------------------------------------
# 2. Create / connect SQLite database
# --------------------------------------------------

conn = sqlite3.connect("platform_analytics.db")

# --------------------------------------------------
# 3. Export DataFrame to SQLite
# --------------------------------------------------

platform.to_sql(
    "platform_statistics",
    conn,
    if_exists="replace",
    index=False
)

print("Platform data exported successfully!")

# --------------------------------------------------
# 4. Check number of rows
# --------------------------------------------------

result = pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM platform_statistics",
    conn
)

print("\nTotal rows:")
display(result)

# --------------------------------------------------
# 5. Display first 5 rows
# --------------------------------------------------

result = pd.read_sql(
    "SELECT * FROM platform_statistics LIMIT 5",
    conn
)

print("\nFirst 5 rows:")
display(result)

# --------------------------------------------------
# 6. Close connection
# --------------------------------------------------

conn.close()

print("\nSQLite database connection closed.")

Platform data exported successfully!

Total rows:

   total_rows
0          17

First 5 rows:

,platform,monthly_active_users_billions,year_over_year_growth_pct,avg_daily_time_minutes,primary_age_group,primary_content_format,avg_engagement_rate_pct,social_commerce_adoption_pct,headquarters_country,founded_year,data_source
0,Facebook,3.07,2.5,33,25-34,Mixed/Video,1.5,60.9,USA,2004,Statista/Meta
1,Instagram,3.00,13.0,35,18-34,Reels/Stories,2.2,35.0,USA,2010,Meta/Reuters
2,YouTube,2.58,5.5,48,18-49,Long/Short Video,1.9,22.0,USA,2005,Statista
3,WhatsApp,3.00,4.0,28,25-44,Messaging,0.0,15.0,USA,2009,Meta
4,TikTok,1.99,17.0,58,18-24,Short-Form Video,2.8,43.8,China,2016,Statista

SQLite database connection closed.